### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-travis-build#1]
@pascalgrimaud can you plz update the dependencies. I dont want to do from windows as it might have some different binaries

**Comment by deepu105** [comment]
this could be the reason of phantomjs failing after dependency update as the no-cache build passed always

**Comment by pascalgrimaud** [comment]
Yes I will have a closed look to this, and will update

**Comment by pascalgrimaud** [comment]
Just updated entire node_modules
I really hope it won't break anything in our travis build... :pray: 
Can you let this ticket opened just a few hours => I'll try to monitor the travis build :construction_worker:

**Comment by deepu105** [comment]
ok sure, its seems to be passing btw

Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
Seems to be ok now

**Comment by deepu105** [comment]
@pascalgrimaud its seems to be back again today I had to restart the build again may be we should do that copy manually part :cry:

**Comment by pascalgrimaud** [comment]
oh bad news! I will work on it today, with your suggestions to copy directly the phantomjs 2.1.1 instead of download it

**Comment by pascalgrimaud** [comment]
I look this build : https://travis-ci.org/jhipster/generator-jhipster/builds/118198415
I can see 2 builds which were running during 49min :
- https://travis-ci.org/jhipster/generator-jhipster/jobs/118198418
- https://travis-ci.org/jhipster/generator-jhipster/jobs/118198419

Here some logs:
```
2016-03-24 10:52:48.209 DEBUG 5542 --- [ost-startStop-1] c.m.m.c.liquibase.AsyncSpringLiquibase   : Starting Liquibase synchronously
2016-03-24 10:52:51.888 ERROR 5542 --- [ost-startStop-1] liquibase                                : classpath:config/liquibase/master.xml: classpath:config/liquibase/changelog/20160208210109_added_entity_constraints_TestEntity.xml::20160208210109::jhipster: Change Set classpath:config/liquibase/changelog/20160208210109_added_entity_constraints_TestEntity.xml::20160208210109::jhipster failed.  Error: Column "TEST_ENTITYS_ID" not found; SQL statement:
ALTER TABLE PUBLIC.test_entity_user_many_to_many ADD CONSTRAINT fk_test_entity_user_many_to_many_user_id FOREIGN KEY (test_entitys_id) REFERENCES PUBLIC.test_entity (id) [42122-191] [Failed SQL: ALTER TABLE PUBLIC.test_entity_user_many_to_many ADD CONSTRAINT fk_test_entity_user_many_to_many_user_id FOREIGN KEY (test_entitys_id) REFERENCES PUBLIC.test_entity (id)]
liquibase.exception.DatabaseException: Column "TEST_ENTITYS_ID" not found; SQL statement:
ALTER TABLE PUBLIC.test_entity_user_many_to_many ADD CONSTRAINT fk_test_entity_user_many_to_many_user_id FOREIGN KEY (test_entitys_id) REFERENCES PUBLIC.test_entity (id) [42122-191] [Failed SQL: ALTER TABLE PUBLIC.test_entity_user_many_to_many ADD CONSTRAINT fk_test_entity_user_many_to_many_user_id FOREIGN KEY (test_entitys_id) REFERENCES PUBLIC.test_entity (id)]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:301)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:107)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1251)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1234)
```

I'm not sure phantomjs is related to these errors.
Should I restart it for trying to rebuild ?

**Comment by deepu105** [comment]
not these these are after I restarted, this is another issue im pushing a fix

**Comment by deepu105** [comment]
before restart many failed with phantom js issue

**Comment by pascalgrimaud** [comment]
Ok thanks @deepu105 
I really don't understand why Travis has so much problem to download this phantomjs from bitbucket, so as you suggested, let's use our cache system
